# Generated by Django 4.1.3 on 2022-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.CharField(blank=True, max_length=10)),
                ('shirina', models.CharField(blank=True, max_length=10)),
                ('visota', models.CharField(blank=True, max_length=10)),
                ('mark', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('enter_date', models.DateField(auto_now_add=True, db_index=True)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/media/site_cards')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/media/site_cards')),
            ],
        ),
    ]
