# Generated by Django 4.1.1 on 2022-09-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10)),
                ('number', models.FloatField(max_length=15)),
                ('enter_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
