# Generated by Django 4.1.1 on 2022-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.IntegerField(max_length=15),
        ),
    ]
