# Generated by Django 4.1.3 on 2022-12-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_shine_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shine',
            name='image_2',
        ),
    ]
