# Generated by Django 4.1.3 on 2022-12-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_shine_cost_remove_shine_mark_alter_shine_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shine',
            name='radius',
        ),
        migrations.AddField(
            model_name='shine',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
