# Generated by Django 4.1.3 on 2023-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_shine_short_note_alter_shine_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shine',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shine',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='shine',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='shine',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='shine',
            name='note',
        ),
        migrations.AddField(
            model_name='shine',
            name='href',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shine',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
