# Generated by Django 4.1.3 on 2023-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_remove_shine_image_remove_shine_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shine',
            name='href',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
