# Generated by Django 4.2.1 on 2023-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='time1',
            field=models.TextField(blank=True),
        ),
    ]
